#!/usr/bin/env bash

ZK_PATH=${ZK_PATH:-$HOME/.zk/}
ZK_TEMPLATE=${ZK_TEMPLATE:-$ZK_PATH/templates/}
mapfile -t ZK_WORKSPACES < <(find "$ZK_PATH" -type d)

if [ ! -d "$ZK_PATH" ]; then
  mkdir -p "$ZK_PATH"
fi

RED="$(tput setaf 196)"
GREEN="$(tput setaf 82)"
BLUE="$(tput setaf 87)"

function help() {
  cat <<EOF
$(_text "$BLUE" "zk | A Zettelkasten Helper")

$(_text "$BLUE" "Usage")
  zk FLAG <FLAG_INPUT> COMMAND INPUT
  zk -h | zk help

$(_text "$BLUE" "Commands")
  add FILENAME WORKSPACE       Add new note
  fzf WORKSPACE                Search all files with fzf
  journal DATE WORKSPACE       Add new journal entry
  list                         List all files

$(_text "$BLUE" "Flags")
  -h            Displays this message and exits
  --help        Displays this message and exits
  -d            Search directories
EOF
}

function _text() {
  local color text reset
  color=$1
  text=$2
  reset=$(tput sgr0)

  echo -e "${color}${text}${reset}"
}

function _error() {
  local message=$1

  _text "$RED" "Error: $message"
}

function _display_all_files() {
  local workspace=$1

  find "$ZK_PATH/$workspace" -type f &>/dev/null | sed -E "s|$ZK_PATH\/||"
}

function _display_workspaces() {
  printf '%s\n' "${ZK_WORKSPACES[@]}"
}

function _list() {
  if [[ "$DIR" -eq 1 ]]; then
    _display_workspaces
  else
    _display_all_files
  fi
  exit 0
}

function _fzf_files() {
  local zk_files=()
  local open_files=()

  if [ -n "$1" ]; then
    workspace="$ZK_PATH/$1"
  fi

  if [ ! -d "$workspace" ]; then
    _error "Workspace $1 does not exist"
    exit 1
  fi

  mapfile -t zk_files < <(_display_all_files "$workspace" | fzf -m --preview "bat $ZK_PATH/{+}")

  if [ -z "${zk_files[*]}" ]; then
    exit 1 # Silent quit
  fi

  for file in "${zk_files[@]}"; do
    open_files+=("$HOME/.zk/$file")
  done
  $EDITOR "${open_files[@]}"
  exit 0
}

function _add_note() {
  local file=$1
  local zk_workspace=$2

  [[ -z "$file" ]] && {
    _error "No file specified!"
    exit 1
  }
  [[ -z "$zk_workspace" ]] && zk_workspace=$(_display_workspaces | fzf --preview "eza -la $ZK_PATH/{}")
  touch "$zk_workspace/$file.md" && $EDITOR "$file.md"
  exit 0
}

function _apply_template() {
  local template="$ZK_TEMPLATE/$1"
  local destination=$2

  if [ ! -f "$destination" ]; then
    if [ ! -f "$template" ]; then
      touch "$destination"
    else
      cat "$template" >>"$destination"
    fi
  else
    return 0
  fi
}

function _journal_parser() {
  local date=$1
  local destination=$2
  local replacements sed_script

  declare -A replacements=(
    ["{{title}}"]="$filename"
    ["{{day}}"]="$day"
    ["{{week}}"]="$week"
    ["{{month}}"]="$month"
    ["{{year}}"]="$year"
    ["{{workspace}}"]="$workspace"
  )

  sed_script=""
  for pattern in "${!replacements[@]}"; do
    replacement="${replacements[$pattern]}"
    sed_script+="s|$pattern|$replacement|g;"
  done

  sed_script=${sed_script%%;}

  sed -i "$sed_script" "$destination"
}

function _get_dates() {
  day=$(date +%F)
  month="$(date +%Y-%m)"
  week="$(date +%Y)-W$(echo "$(date +%V) + 1" | bc)"
  year=$(date +%Y)
}

function _add_journal_entry() {
  local date
  local is_journal=1
  local requested_date=$1
  local val

  if [ -n "$2" ]; then
    workspace="$ZK_PATH/$2"
    mkdir -p "$workspace"
  fi

  _get_dates

  if [[ "$requested_date" == "day" ]]; then
    date="$day"
  elif [[ "$requested_date" == "month" ]]; then
    date="$month"
  elif [[ "$requested_date" == "week" ]]; then
    date="$week"
  elif [[ "$requested_date" == "year" ]]; then
    date="$year"
  else
    _error "No date specified!"
    echo "Usage: zk journal day/week/month/year workspace"
    exit 1
  fi

  [[ -z "$workspace" ]] && workspace=$(_display_workspaces | fzf --preview "eza -la $ZK_PATH/{}")

  filename="$date"
  _apply_template "$requested_date.md" "$workspace/$filename.md" "$is_journal"
  val=$?
  _journal_parser "$date" "$workspace/$filename.md"
  [[ "$val" -eq 0 ]] && $EDITOR "$workspace/$filename.md"
  exit 0
}

while getopts ":hd-" opt; do
  case "$opt" in
  h)
    help
    exit 0
    ;;
  -)
    break
    ;;
  d)
    DIR=1
    ;;
  ?)
    _text "$RED" "Error: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

while [[ $# -gt 0 ]]; do
  case "$1" in
  --help)
    help
    exit 0
    ;;
  fzf)
    shift
    _fzf_files "$@" # workspace
    ;;
  add)
    shift
    _add_note "$@" # filename, workspace
    ;;
  journal)
    shift
    _add_journal_entry "$@" # date, workspace
    ;;
  list)
    _list
    ;;
  *)
    _list
    ;;
  esac
done
